# Generated by Django 2.2.24 on 2021-07-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.TextField(blank=True, default='')),
                ('text_on_hover', models.TextField(blank=True, default='')),
                ('published_date', models.CharField(blank=True, default='', max_length=100)),
                ('additional_info', models.TextField(blank=True, default='')),
                ('cartoon', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
